export const categoryList = [
  {
    id: 1,
    value: 'place',
    label: '📍 Lokasi',
  },
  {
    id: 2,
    value: 'dish',
    label: '🍛 Makan',
  },
];

export const ratingList = [
  {
    id: 1,
    value: '1',
    label: '1 🌟',
  },
  {
    id: 2,
    value: '2',
    label: '2 🌟',
  },
  {
    id: 3,
    value: '3',
    label: '3 🌟',
  },
  {
    id: 4,
    value: '4',
    label: '4 🌟',
  },
  {
    id: 5,
    value: '5',
    label: '5 🌟',
  },
];

export const dataList = [
  {
    id: 1,
    title: 'Chortiez & Co',
    township: 'Kangar',
    url:  'https://maps.app.goo.gl/3WfZiE1U3HtcbTep9',
    category: 'place', 
    cuisine: 'western',
    rating: 5,
    price: 20,
    coverSrc: '/images/lokasi/chortiez.jpeg',
  },
  {
    id: 2,
    title: 'Warung Tepi Sawah 2769',
    township: 'Kangar',
    url: 'https://maps.app.goo.gl/YrFtQdH3uZXiSXmv5',
    category: 'place',
    cuisine: 'sarapan',
    rating: 4,
    price: 1,
    coverSrc: '/images/lokasi/warung_tepi_sawah.jpeg',
  },
   {
    id: 3,
    title: 'Rico Cafe & Western',
    township: 'Kangar',
    url: 'https://maps.app.goo.gl/YrFtQdH3uZXiSXmv5',
    category: 'place',
    cuisine: 'sarapan',
    rating: 4,
    price: 1,
    coverSrc: '/images/lokasi/warung_tepi_sawah.jpeg',
  },
   {
    id: 4,
    title: 'Warung Tepi Sawah 2769',
    township: 'Kangar',
    url: 'https://maps.app.goo.gl/YrFtQdH3uZXiSXmv5',
    category: 'place',
    cuisine: 'sarapan',
    rating: 4,
    price: 1,
    coverSrc: '/images/lokasi/warung_tepi_sawah.jpeg',
  },
   {
    id: 5,
    title: 'Warung Tepi Sawah 2769',
    township: 'Kangar',
    url: 'https://maps.app.goo.gl/YrFtQdH3uZXiSXmv5',
    category: 'place',
    cuisine: 'sarapan',
    rating: 4,
    price: 1,
    coverSrc: '/images/lokasi/warung_tepi_sawah.jpeg',
  },
   {
    id: 6,
    title: 'Warung Tepi Sawah 2769',
    township: 'Kangar',
    url: 'https://maps.app.goo.gl/YrFtQdH3uZXiSXmv5',
    category: 'place',
    cuisine: 'sarapan',
    rating: 4,
    price: 1,
    coverSrc: '/images/lokasi/warung_tepi_sawah.jpeg',
  },
   {
    id: 7,
    title: 'Warung Tepi Sawah 2769',
    township: 'Kangar',
    url: 'https://maps.app.goo.gl/YrFtQdH3uZXiSXmv5',
    category: 'place',
    cuisine: 'sarapan',
    rating: 4,
    price: 1,
    coverSrc: '/images/lokasi/warung_tepi_sawah.jpeg',
  },
  
];