export const categoryList = [
  {
    id: 1,
    value: 'place',
    label: '📍 Lokasi',
  },
  {
    id: 2,
    value: 'dish',
    label: '🍛 Makan',
  },
];

export const ratingList = [
  {
    id: 1,
    value: '1',
    label: '1 🌟',
  },
  {
    id: 2,
    value: '2',
    label: '2 🌟',
  },
  {
    id: 3,
    value: '3',
    label: '3 🌟',
  },
  {
    id: 4,
    value: '4',
    label: '4 🌟',
  },
  {
    id: 5,
    value: '5',
    label: '5 🌟',
  },
];

export const dataList = [
  {
    id: 1,
    title: 'Chortiez & Co',
    township: 'Kangar',
    url:  'https://maps.app.goo.gl/3WfZiE1U3HtcbTep9',
    category: 'place', 
    cuisine: 'western',
    rating: 5,
    price: 20,
    coverSrc: '/images/lokasi/chortiez.jpeg',
  },
  {
    id: 2,
    title: 'Warung Tepi Sawah 2769',
    township: 'Kangar',
    url: 'https://maps.app.goo.gl/YrFtQdH3uZXiSXmv5',
    category: 'place',
    cuisine: 'sarapan',
    rating: 4,
    price: 1,
    coverSrc: '/images/lokasi/warung_tepi_sawah.jpeg',
  },
   {
    id: 3,
    title: 'Rico Cafe & Western',
    township: 'Kangar',
    url: 'https://maps.app.goo.gl/XScNXPZg44NhvjiJ9',
    category: 'place',
    cuisine: 'western',
    rating: 4,
    price: 1,
    coverSrc: '/images/lokasi/rico_cafe.jpeg',
  },
   {
    id: 4,
    title: 'Saville Pastries & Coffee',
    township: 'Kangar',
    url: 'https://maps.app.goo.gl/WLUPdPyE3k4M2rBy9',
    category: 'place',
    cuisine: 'coffee',
    rating: 4,
    price: 1,
    coverSrc: '/images/lokasi/saville.jpg',
  },
   {
    id: 5,
    title: 'Eighty Nine Celcius Perlis',
    township: 'Kangar',
    url: 'https://maps.app.goo.gl/kHEUPJnoQ91TMDQ48',
    category: 'place',
    cuisine: 'western',
    rating: 5,
    price: 1,
    coverSrc: '/images/lokasi/89.jpeg',
  },
   {
    id: 6,
    title: 'The Houze Cafe',
    township: 'Kangar',
    url: 'https://maps.app.goo.gl/N8uXXYjnmjJhnVYn6',
    category: 'place',
    cuisine: 'western',
    rating: 4,
    price: 1,
    coverSrc: '/images/lokasi/houze_cafe.jpeg',
  },
   {
    id: 7,
    title: 'Capati Arau',
    township: 'Arau',
    url: 'https://maps.app.goo.gl/SJdXRY2MKYETJb8y9',
    category: 'place',
    cuisine: 'sarapan',
    rating: 4,
    price: 1,
    coverSrc: '/images/lokasi/capati_arau.jpeg',
  },
   {
    id: 7,
    title: 'Warung Bang Teh',
    township: 'Kangar',
    url: 'https://maps.app.goo.gl/T2wrXiHMK97t9D3F8',
    category: 'place',
    cuisine: 'sarapan',
    rating: 5,
    price: 1,
    coverSrc: '/images/lokasi/warung_bang_teh.jpeg',
  },
  
];